const biographies = {
    
        "en": "Ruth Scholz is a successful 29-year-old clarinetist with a rich experience of playing in orchestras and chamber ensembles.\nShe completed two years of compulsory service in the IDF Orchestra. She then completed a bachelor's degree in musical performance from the Buchmann-Mehta School of Music (Tel Aviv University).\nRuth holds an additional BA in Economics and Business Administration from the Open University of Israel.\nCurrently, she serves as Co-principal clarinetist of the Haifa Symphony Orchestra since 2021, where she has been able to perform several times as a soloist under the baton of Maestro Yoel Levi.\nRuth plays regularly in the orchestra's chamber music series.\nIn addition to her musical role in the orchestra, Ruth is also the orchestra's social media director.\nRuth founded a Choro ensemble in which she also plays, called \"Choro das Mocas\".\nHer achievements include many prizes in prestigious competitions, including third place in the national wind competition in Kfar Saba, receiving a scholarship from the America-Israel Cultural Foundation and the Netanya Municipality scholarship to encourage young artists, as well as participation in master classes in Israel and around the world.\nRuth also masters bass clarinet and saxophone, frequently performing with the Haifa Big Band.",
    
        "he": "רות שולץ היא קלרניטנית מצליחה בת 29 עם רקע עשיר של ניסיון בנגינה בתזמורת, נגינה קאמרית וכסולנית. היא השלימה שירות חובה של שנתיים בתזמורת צה\"ל. לאחר מכן השלימה תואר ראשון בביצוע מוסיקלי מבית הספר למוזיקה בוכמן-מהטה (אוניברסיטת ת\"א). רות מחזיקה בתואר ראשון נוסף בכלכלה ומנהל עסקים מהאוניברסיטה הפתוחה. כיום, היא משמשת כקלרניטנית ראשית עמיתה בתזמורת הסימפונית חיפה, החל מ-2021, שם זכתה להופיע מספר פעמים כסולנית תחת שרביטו של מאסטרו יואל לוי. רות מנגנת באופן קבוע בסדרת המוזיקה הקאמרית של התזמורת. בנוסף לתפקידה המוסיקלי בתזמורת, רות היא גם המנהלת מדיה חברתית בתזמורת. רות הקימה אנסמבל <span dir='ltr'>Choro</span> שבו היא גם מנגנת, האנסמבל נקרא <span dir='ltr'>Choro das Mocas</span>. הישגיה כוללים פרסים רבים בתחרויות יוקרתיות, וביניהם מקום שלישי בתחרות כלי הנשיפה הלאומית בכפר סבא, קבלת מלגת קרן התרבות אמריקה-ישראל והמלגה לעידוד אמנים צעירים מטעם עיריית נתניה וכן השתתפות בכיתות אמן בארץ ובעולם. רות שולטת גם בקלרינט בס ובסקסופון, והיא מופיעה לעיתים קרובות עם תזמורת ה-<span dir='ltr'>Big Band</span> של חיפה",
                      
        "de": "Ruth Scholz ist eine erfolgreiche 29-jährige Klarinettistin mit reichhaltiger Erfahrung als Orchestermusikerin und Kammermusikerin. Sie leistete zwei Jahre Pflichtdienst im IDF-Orchester. Anschließend absolvierte sie einen Bachelor-Abschluss in musikalischer Darbietung an der Buchmann-Mehta School of Music (Tel Aviv University). Ruth hat zudem einen Bachelor-Abschluss in Wirtschafts- und Betriebswirtschaftslehre von der Open University. Derzeit ist sie Soloklarinettistin im Haifa Symphonie-Orchester, wo sie seit 2021 mehrmals als Solistin unter der Leitung von Maestro Yoel Levi auftreten konnte. Ruth spielt regelmäßig in der Kammermusikreihe des Orchesters. Neben ihrer musikalischen Rolle im Orchester ist Ruth auch die Social-Media-Direktorin des Orchesters. Ruth gründete ein Choro-Ensemble, in dem sie auch selber mitspielt. Das Ensemble heißt \"Choro das Mocas\". Zu ihren Leistungen zählen zahlreiche Preise bei renommierten Wettbewerben, darunter der dritte Platz beim nationalen Bläserwettbewerb in Kfar Saba, ein Stipendium der Amerikanisch-Israelischen Kulturstiftung und das Netanya-Stipendium zur Förderung junger Künstler, sowie die Teilnahme an Meisterkursen in Israel und der ganzen Welt. Ruth beherrscht auch Bassklarinette und Saxophon und tritt häufig mit der Haifa Big Band auf."
        
};

// Function to load the biography content into the appropriate element
function loadBiographyContent(lang) {
        const bioContent = biographies[lang];
        const bioElement = document.getElementById(`bio-${lang}`);
        bioElement.innerHTML = bioContent; // Load content into the element
    }
